version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - composer install
  build:
    commands:
      - echo "Building the application..."
  post_build:
    commands:
      - echo "Build completed."
artifacts:
  files: '**/*'

